- name: Deploy Django app with Docker
  hosts: webservers
  become: yes

  tasks:
    - name: Ensure /opt/myapp exists
      file:
        path: /opt/myapp
        state: directory

    - name: Copy docker-compose file
      copy:
        src: ansible/files/docker-compose.yml
        dest: /opt/myapp/docker-compose.yml

    - name: Copy Dockerfile
      copy:
        src: ansible/files/Dockerfile
        dest: /opt/myapp/Dockerfile

    - name: Start Docker containers
      command:
        cmd: docker compose up -d
        chdir: /opt/myapp
